filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'examples/*'
before_commands:
    - 'composer install --prefer-source'
build:
    tests:
        override:
            - phpcs-run --standard=./vendor/chadicus/coding-standard/Chadicus/ruleset.xml src
tools:
    php_analyzer: true
    php_mess_detector: true
    sensiolabs_security_checker: true
    php_loc:
        excluded_dirs:
            - vendor
            - tests
            - examples
    php_pdepend: true
    php_sim: true
build_failure_conditions:
    - 'elements.rating(<= B).new.exists'
    - 'issues.label("coding-style").new.exists'
    - 'issues.severity(>= MAJOR).new.exists'
    - 'project.metric("scrutinizer.quality", < 6)'
