branches:
  except: incubator
language: php
php:
  - 5.6
  - 5.5
  - 5.4
services: mongodb
before_script:
  - composer self-update || true
  - echo 'extension="mongo.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: ./build.php
