language: php
php:
  - 5.6
  - 7.0
  - 7.1
before_script:
  - composer self-update
  - yes '' | pecl install -f mongodb-1.1
  - composer install
script: ./vendor/bin/phpunit --coverage-clover clover.xml
after_success: ./vendor/bin/coveralls -v
