language: php
php:
  - 7.0
  - 7.1
  - 7.2
before_script:
  - composer self-update
  - composer install
script: ./vendor/bin/phpunit --coverage-clover clover.xml
after_success: ./vendor/bin/coveralls -v
